name: SIH Training



# Build settings
markdown: kramdown
remote_theme: niklasbuschmann/contrast

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
